from fpdf import FPDF
import os

class SoilReport(FPDF):
    def header(self):
        self.set_font("Arial", "B", 20)
        self.set_text_color(79, 70, 229)
        self.cell(0, 10, "SOIL_SCAN ANALYSIS REPORT", ln=True, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} - Generated by soil_scan AI", align="C")

def generate_pdf_report(data, image_path, output_path):
    pdf = SoilReport()
    pdf.add_page()
    
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "1. Executive Summary", ln=True)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"Date: {data['date']}", ln=True)
    pdf.cell(0, 8, f"Sample Weight: {data['weight_g']}g", ln=True)
    pdf.cell(0, 8, f"Particle Count: {data['count']}", ln=True)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"Concentration: {data['concentration']} p/kg", ln=True)
    
    color = (255, 200, 200) if data['risk'] == "High" else (200, 255, 200)
    pdf.set_fill_color(*color)
    pdf.cell(40, 10, f"RISK: {data['risk']}", ln=True, fill=True, align="C")
    pdf.ln(5)

    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "2. UV Detection Visual", ln=True)
    if os.path.exists(image_path):
        pdf.image(image_path, x=10, w=180)
    pdf.ln(5)

    pdf.add_page()
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, "3. Remediation Suggestions", ln=True)
    pdf.set_font("Arial", "", 11)
    for advice in data['suggestions']:
        pdf.multi_cell(0, 8, f"- {advice}")
        pdf.ln(2)

    pdf.output(output_path)
    return output_path